name: workflow-ci-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn>=1.5
      - pandas>=2.1
      - numpy>=1.26
      - matplotlib>=3.8
